### ISSUE TITLE
Installing problem

### ISSUE THREAD

**Issue by MAHMOUDRR707** [linqian66/allennlp-0.8.4#1] opened 2024-08-30 16:37 UTC
I got this problem while I am installing allennlp  as I went throw all your steps 

`
Collecting spacy<2.2,>=2.1.0 (from allennlp)
  Using cached spacy-2.1.9.tar.gz (30.7 MB)
  error: subprocess-exited-with-error
  
  × pip subprocess to install build dependencies did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  Installing build dependencies ... error
error: subprocess-exited-with-error

× pip subprocess to install build dependencies did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
`

**Comment by linqian66** [comment] 2024-09-03 02:32
Duplicate of nusnlp/LIF#2

**Closed by linqian66** 2024-09-03 02:32 UTC
